### ISSUE TITLE
Remove reference to files from section 3

### ISSUE THREAD

**Issue by eliasmalik** [foundersandcoders/api-workshop#32]
https://github.com/foundersandcoders/api-workshop/blob/master/03-xmlhttprequest.md

> ...which you can then use to query a server or file of your choice.

> url: The requested URL (in this case a local file path: "xmlhttp_info.txt") - in many cases this will be the URL of the server you are querying.

XHR cannot be used to query local files, since the JS runtime is sandboxed by the browser. XHR will _only_ accept URLs. If you do something like `xhr.open('GET', 'foo.txt')`, it will be interpreted as `http://<ORIGIN>/foo.txt`

**Comment by ghassanmas** [comment]
My suggestion is that we have to clarify that the default action of the xhr object is the same domain origin, not the CORS, so if the full url is not specified like the example you mentioned it will be as  `http://<current_origin>/foo.txt`. I think we should also motion that the API is special case where the HOST of the API allows requested are the sent not from the same origin to be served.
